import Head from 'next/head'
import styles from '../styles/Home.module.scss'
import {useState} from "react";
import clsx from "clsx";
import Column from "../components/Column/Column";
import {events} from "../constants/events";
import RecentEvent from "../components/RecentEvent/RecentEvent";
import {articles} from "../constants/articles";
import Article from "../components/Article/Article";
import {devResources} from "../constants/dev-resources";
import {erc223} from "../constants/erc-223";

export default function Home() {
  const [activeTab, setActiveTab] = useState(0);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className={styles.header}>ERC-223</header>
      <main>
        <div className={styles.tabs}>
          <div className={clsx(styles.tab, activeTab === 0 && styles.active)}>
            <button onClick={() => {
              setActiveTab(0);
            }} className={styles.tabButton}>Resources</button>
            <div className={styles.resources}>
              <Column title="📝 Articles">
                {articles.map(({url, title, description}) => {
                  return <Article key={title} url={url} title={title} description={description} />
                })}
              </Column>
              <Column title="📔 ERC-223">
                {erc223.map(({url, title, description}) => {
                  return <Article key={title} url={url} title={title} description={description} />
                })}
              </Column>
              <Column title="👨🏻‍💻 Development resources">
                {devResources.map(({url, title, description}) => {
                  return <Article key={title} url={url} title={title} description={description} />
                })}
              </Column>
            </div>
          </div>
          <div className={clsx(styles.tab, activeTab === 1 && styles.active)}>
            <button onClick={() => {
              setActiveTab(1);
            }} className={styles.tabButton}>Events</button>
            <div className={styles.eventsTabContent}>
              <Column title="📅 Latest events">
                {events.map(({url, title, date}) => {
                  return <RecentEvent key={title} url={url} title={title} date={date} />
                })}
              </Column>
            </div>
          </div>
        </div>
      </main>
    </>
  )
}
